export const Translations = {
  copyPage: 'Copier le code de la page',
  deleteComponent: 'Supprimer le bloc',
  copyComponent: 'Copier le  bloc',
  searchComponent: 'Rechercher un bloc',
  copySuccess: 'Le code a bién été copié',
  copyInstructions: 'vous pouvez le coller sur une autre page (CTRL + V)',
  addComponent: 'Ajouter un bloc',
  responsiveView: 'Vue responsive',
  addItem: 'Ajouter un élément',
  deleteItem: "Supprimer l'élément",
  rollback: 'Rétablir',
  deleteItemConfirm: 'Le bloc a bien été supprimé',
  unknownComponent: 'Bloc inconnu',
  save: 'Sauvegarder',
  close: 'Fermer',
  poweredBy: 'Propulsé par',
  noContent: `Vous n'avez pas encore de contenu`,
  useTemplate: 'Utilisez un template',
}
